name: leetcode test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install cmake g++ make
    - name: test
      run: |
        mkdir build && cd build && cmake .. && make
        ./test